### ISSUE TITLE
Significant library size

### ISSUE THREAD

**Issue by marbemac** [udecode/zustand-x#71]
**Description**

See title - zustand-x is sitting at about 90kb minified (zustood was 30kb minified). There might be some low hanging fruit? For example, it looks like all of lodash is bundled in - not sure what else, I haven't had a lot of time to check.

**Comment by zbeyens** [comment]
We've replaced rollup with tsup. Lodash is indeed in fault, I'll update the imports.

**Comment by zbeyens** [comment]
Should be fixed in latest
