### ISSUE TITLE
Can't seem to type store options

### ISSUE THREAD

**Issue by wmonecke** [udecode/zustand-x#76]
**Description**

I am trying to type a createStore call but somehow `persist: true` keeps throwing an error.

<img width="980" alt="image" src="https://github.com/udecode/zustand-x/assets/24256469/69ec06cf-cf7f-4968-9d4d-b27566e54265">

How can I type createStore properly?

Thank you very much!

**Comment by wmonecke** [comment]
Nevermind, my mistake!

**Comment by elijaholmos** [comment]
@wmonecke what was the problem?
